services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:80"
    tty: true
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211