services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:80"
    tty: true
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"
    env_file:
      - .env
  worker:
    build:
      context: ./worker
      dockerfile: ./docker/Dockerfile
    tty: true
    restart: always
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"
    # env_file:
    #   - .env
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211