name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: allo-masakari-backend
  ECR_WORKER_REPOSITORY: allo-masakari-backend-worker
  TFSTATE_S3_BUCKET_NAME: yukinissie-tfstate
  TFSTATE_S3_BUCKET_KEY: allo-misakari-backend/terraform.tfstate

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ap-northeast-1

      - uses: aws-actions/amazon-ecr-login@v1
        id: amazon-ecr-login

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: ./api
          file: ./api/docker/Dockerfile
          platforms: linux/arm64
          tags: ${{ steps.amazon-ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: ./worker
          file: ./worker/docker/Dockerfile
          platforms: linux/arm64
          tags: ${{ steps.amazon-ecr-login.outputs.registry }}/${{ env.ECR_WORKER_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Download ecspresso
        uses: kayac/ecspresso@v1
        with:
          version: v1.7.12

      - name: Register task definition
        run: ecspresso --config config.yml register
        working-directory: ./infra/masakari-backend/ecspresso

      - name: Deploy to ecs
        run: ecspresso --config config.yml deploy --latest-task-definition
        working-directory: ./infra/masakari-backend/ecspresso
